config/routes.rb
BoutinYoannFrameworkProject::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :anecdotes, only: [:create]
  resources :personnes, only: :create
  resources :scenes, only: :create
  resources :chapitres, only: :create
  root 'static_pages#home'
  match '/edit_user', to: 'users#edit', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help', to: 'static_pages#help' , via: 'get'
  match '/about', to: 'static_pages#about' , via: 'get'
  match '/personne', to: 'static_pages#personne', via: 'get'
  match '/chapitre', to: 'static_pages#chapitre', via: 'get'
  match '/scene', to: 'static_pages#scene', via: 'get'
  match '/anecdote', to: 'static_pages#anecdote', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home 
  end

  def help
  end

  def about
  end

  def anecdote
    if signed_in?
      @anecdote  = current_user.anecdotes.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def scene
    if signed_in?
      @scene  = current_user.scenes.build
      @feed_items_scene = current_user.feed_scene.paginate(page: params[:page])
    end
  end

  def chapitre
    if signed_in?
      @chapitre  = current_user.chapitres.build
      @feed_items_chapitre = current_user.feed_chapitre.paginate(page: params[:page])
    end
  end

  def personne
    if signed_in?
      @personne  = current_user.personnes.build
      @feed_items_personne = current_user.feed_personne.paginate(page: params[:page])
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>A propos</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/anecdote.html.erb
<% if signed_in? %>  
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/anecdote_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Anecdotes Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Projet BOUTIN Yoann</h1>

    <h2>
      Bienvenue sur la page principale du projet de Framework de BOUTIN Yoann.
    </h2>

    <%= link_to "Inscription!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/static_pages/chapitre.html.erb
<% if signed_in? %>  
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/chapitre_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Chapitres Feed</h3>
      <%= render 'shared/feed_chapitre' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Projet BOUTIN Yoann</h1>

    <h2>
      Bienvenue sur la page principale du projet de Framework de BOUTIN Yoann.
    </h2>

    <%= link_to "Inscription!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>Aide</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="center hero-unit">
    <h1>Bienvenue !</h1>
    <%= link_to "Chapitre", chapitre_path,
                                class: "btn btn-large btn-primary" %>
    <%= link_to "Scene", scene_path,
                                class: "btn btn-large btn-primary" %>
    <%= link_to "Anecdote", anecdote_path,
                                class: "btn btn-large btn-primary" %>
      
    <%= link_to "Personne", personne_path,
                                class: "btn btn-large btn-primary" %>                        
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Projet BOUTIN Yoann</h1>

    <h2>
      Bienvenue sur la page principale du projet de Framework de BOUTIN Yoann.
    </h2>

    <%= link_to "Inscription!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/static_pages/personne.html.erb
<% if signed_in? %>  
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/personne_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Personnes Feed</h3>
      <%= render 'shared/feed_personne' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Projet BOUTIN Yoann</h1>

    <h2>
      Bienvenue sur la page principale du projet de Framework de BOUTIN Yoann.
    </h2>

    <%= link_to "Inscription!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/static_pages/scene.html.erb
<% if signed_in? %>  
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/scene_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Scenes Feed</h3>
      <%= render 'shared/feed_scene' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Projet BOUTIN Yoann</h1>

    <h2>
      Bienvenue sur la page principale du projet de Framework de BOUTIN Yoann.
    </h2>

    <%= link_to "Inscription!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>
<% end %>