config/routes.rb
BoutinYoannFrameworkProject::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :anecdotes, only: [:create]
  resources :personnes, only: :create
  resources :scenes, only: :create
  resources :chapitres, only: :create
  root 'static_pages#home'
  match '/edit_user', to: 'users#edit', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help', to: 'static_pages#help' , via: 'get'
  match '/about', to: 'static_pages#about' , via: 'get'
  match '/personne', to: 'static_pages#personne', via: 'get'
  match '/chapitre', to: 'static_pages#chapitre', via: 'get'
  match '/scene', to: 'static_pages#scene', via: 'get'
  match '/anecdote', to: 'static_pages#anecdote', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by BOUTIN Yoann
  </small>
  <nav>
    <ul>
      <li><%= link_to "A propos",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Projet Yoann Boutin", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Acceuil", root_path %></li>
          <li><%= link_to "Aide", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Utilisateurs", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Compte <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profil", current_user %></li>
                <li><%= link_to "Parametres", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Deconnexion", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Connexion", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>